site_name: My Docs
site_url: https://makyno.jp/docs/
theme: 
    name: material
    language: 'ja'
plugins:
  - blogging:
      dirs: # The directories to be included
        - blog
  - search:
        language: 'jp'
