site_name: 家族のための資料
site_url: https://makyno.jp/docs/
theme: 
    name: material
    language: 'ja'
extra:
  search:
    language: 'jp'
plugins:
  - blogging:
      dirs: # The directories to be included
        - blog
  - search
