site_name: 家族のための資料
site_url: https://makyno.jp/docs/
theme: 
    name: material
    language: 'ja'
extra:
  search:
    language: 'jp'
  food_tax: 0.08
  with_food_tax: 1.08
  item_tax: 0.1
  with_item_tax: 1.1
plugins:
  - blog:
     blog_dir: .
  - search
  - tags:
      tags_file: tags.md
  - glightbox  
  - macros
nav:
  - index.md
  - usage.md
markdown_extensions:
  - attr_list
  - md_in_html
extra_css:
  - stylesheets/extra.css
